train:
  wandb: True
  device: ~
  local_rank: ~
  exp_name: base_cosine_L

  num_train_steps: 200000
  num_valid_steps: 5000
  save_ckpt_steps: 5000
  batch_size: 16

  learning_rate: !!float 1e-4
  optimizer: Adam
  gamma: cosine

generation:
  batch_size: 1
  samples: 2
  timesteps: 12
  show_process: True

tokenizer: ~
vqvae:
  config_file: moco_vqvae/config/MoCoVQVAEwCD/UCF101/MoCoVQVAEwCD_im128_woPT_dbBSLR.yaml
  checkpoint: experiments/exp_vqvae/MoCoVQVAEwCD_UCF_im128_woPT_dbBSLR_2022-05-12-10-53-49/MoCoVQVAE_wCD_iter100000.pth

dataset:
  name: ucf101
  cname: SingleMoDataset
  pin_memory: True
  shuffle: False
  num_worker: 4
  num_tokens: 576
  train:
    tokens_dir: /home/zhongguokexueyuanzidonghuayanjiusuo/mzsun/codes/MoCo/datasets/UCF101_im128_FPS20/train
  valid:
    tokens_dir: /home/zhongguokexueyuanzidonghuayanjiusuo/mzsun/codes/MoCo/datasets/UCF101_im128_FPS20/valid

model:
  name: base
  num_layer: 24
  embed_dim: 758
  hidden_dim: 1024
  immediate_hidden_dim: 2048
  encoder_opt:
    num_head: 8

  bg_token_length: 256
  id_token_length: 256
  mo_token_length: 64
  max_input_length: 600
  dropout: 0.0

  checkpoint_path: ~
  pretrain_path: ~
  load_strict: ~