dataset:
  name: VideoDiffFrames
  batch_size: 2
  limit: 0.5
  img_size: 256
  num_frames: 16
  num_workers: 2
  shuffle: False
  pin_memory: True
  train:
    idspath: /home/zhongguokexueyuanzidonghuayanjiusuo/mzsun/codes/MoCo/MoCo_VG/datasets/FaceForensics/all_ids.json
    datapath: /home/zhongguokexueyuanzidonghuayanjiusuo/mzsun/codes/MoCo/MoCo_VG/datasets/FaceForensics
  val:
    idspath: /home/zhongguokexueyuanzidonghuayanjiusuo/mzsun/codes/MoCo/MoCo_VG/datasets/FaceForensics/all_ids.json
    datapath: /home/zhongguokexueyuanzidonghuayanjiusuo/mzsun/codes/MoCo/MoCo_VG/datasets/FaceForensics
#    idspath: ~
#    datapath: /home/zhongguokexueyuanzidonghuayanjiusuo/mzsun/codes/MoCo/MoCo_VG/datasets/FaceForensics/valid

model:
  name: MoCoVQVAE_wCD
  pretrain_path: ~
  checkpoint_path: experiments/MoCoVQVAEwCD_Face_im256_16frames_2022-06-09-23-56-54/MoCoVQVAE_wCD_iter125000.pth
  load_strict: True

  num_hiddens: 256
  num_residual_layers: 4
  num_residual_hiddens: 128

  embedding_dim_c: 256
  embedding_dim_m: 256
  num_embeddings_c: 8192
  num_embeddings_m: 8192 # [4096, 9182, ...]

  ds_content: 3
  ds_motion: 5
  ds_identity: 3
  ds_background: 3
  suf_method: conv # [avg_pool, max_pool, conv]
  decoder_type: decoder_woPA
  encoder_mo_type: default

  num_head: 4
  num_group: 4

  ABS_weight: 1.0
  MSE_weight: 0.0
  Gen_weight: 0.1

  decay: 0.99
  if_augcb: 2
  commitment_cost: 0.25
  with_lpips: True
  lpips_factor: 1.0

  disc_name: patchwise
  disc_opt:
    input_nc: 48    # 3channel * 16frames
    n_layers: 3
    ndf: 64
    input_formation: concat_c

train:
  device: ~ # the parameter will be given when training
  local_rank: ~ # the parameter will be given when training
  WANDB_OPEN: True
  find_unused_parameters: True

  # model params
  exp_name: MoCoVQVAEwCD_Face_im256_16frames
  save_path: experiments/

  # train params
  learning_rate: !!float 2e-4
  LRsche: True

  # steps
  num_epochs: 4000
  num_warmup_steps: 0  # null if want to set 0.1 warm up
  num_training_updates: 250000
  num_validation_steps: 2500
  disc_start_step: 50000
  save_ckpt_per_iter: 5000
