train:
  wandb: True
  device: ~
  local_rank: ~
  task: video_prediction
  exp_name: RoboNet_64rs_12f_fps32_stacktrm2_como_firsttwoframes

  deepspeed_config: config/deepspeed/deepspeed_base_fp16_bs16_lr5e-5.json
  num_train_steps: 1000000
  num_valid_steps: 2500
  save_ckpt_steps: 5000
  gamma: cosine
  convert_loss_to_fp32: True

generation:
  batch_size: 1
  topk: -1
  samples: 1
  timesteps: 4
  temperature: 3
  show_process: True

tokenizer:
  type: shareCB # [default, shareCB]
  num_frames: 12  # number of frames encoded by mocovqvae

vqvae:
  config_file: MoCoVQVAE/config/mocovqvae_wcd_sCB/RoboNet/MoCoVQVAEwCD_im64_16frames_co+mo.yaml
  checkpoint: experiments/exp_vqvae/MoCoVQVAEwCDsCB_RoboNet_im64_16frames_co+mo_2022-07-22-21-06-33/MoCoVQVAEwCDsCB_como_iter150000.pth

dataset:
  name: RoboNet
  cname: CustomVPDataset
  pin_memory: False
  shuffle: False
  num_worker: 0
  train:
    tokens_16f_dir: datasets/RoboNet/tokens/im64_co2_mo3/train/FPS32
    tokens_1th_dir: datasets/RoboNet/tokens/im64_co2_mo3_firsttwoframes/train/FPS32
  valid:
    tokens_16f_dir: datasets/RoboNet/tokens/im64_co2_mo3/valid/FPS32
    tokens_1th_dir: datasets/RoboNet/tokens/im64_co2_mo3_firsttwoframes/valid/FPS32

model:
  name: StackTRM2_shareCB_VP_wd

  transformer: stack
  num_layer: 16
  mo_num_layer: 8
  embed_dim: 758
  hidden_dim: 1024
  immediate_hidden_dim: 2048
  encoder_opt:
    num_head: 8

  bg_token_length: 256 # H-32, W-32
  id_token_length: 256  # H-16, W-16
  mo_token_length: 768 # T-12, H-8, W-8
  max_input_length: 800 # max(bg + id + T + cmd, mo + cmd)
  dropout: 0.1

  checkpoint_path: ~
  pretrain_path: ~
  load_strict: True