dataset:
  name: VideoDiffFrames
  batch_size: 8
  limit: 0.5
  img_size: 64
  num_frames: 20
  num_workers: 8
  shuffle: False
  pin_memory: False
  train:
    idspath: ~
    usedfps: FPS25
    datapath: datasets/KTH/frames/train
  val:
    idspath: ~
    usedfps: FPS25
    datapath: datasets/KTH/frames/test

model:
  name: MoCoVQVAE_wCD_shareCB
  pretrain_path: ~
  checkpoint_path: experiments/MoCoVQVAEwCDsCB_KTH_im64_20frames_2022-07-22-13-28-12/MoCoVQVAE_wCD_shareCB_iter150000.pth
  load_strict: True

  num_hiddens: 256
  num_residual_layers: 4
  num_residual_hiddens: 128

  embedding_dim: 256
  num_embeddings: 16384 # [4096, 9182, ...]

  ds_content: 2
  ds_motion: 3
  ds_identity: 2
  ds_background: 2
  suf_method: conv # [avg_pool, max_pool, conv]
  decoder_type: decoder_woPA
  encoder_mo_type: default

  num_head: 4
  num_group: 4

  ABS_weight: 1.0
  MSE_weight: 0.0
  Gen_weight: 0.1

  decay: 0.99
  if_augcb: 2
  commitment_cost: 0.25
  with_lpips: True
  lpips_factor: 1.0

  disc_name: patchwise
  disc_opt:
    input_nc: 60    # 3channel * 20frames
    n_layers: 2
    ndf: 32
    input_formation: concat_c

train:
  device: ~ # the parameter will be given when training
  local_rank: ~ # the parameter will be given when training
  WANDB_OPEN: True
  find_unused_parameters: True

  # model params
  exp_name: MoCoVQVAEwCDsCB_KTH_im64_20frames
  save_path: experiments/

  # train params
  learning_rate: !!float 2e-4
  LRsche: True

  # steps
  num_epochs: 100000
  num_warmup_steps: 0  # null if want to set 0.1 warm up
  num_training_updates: 250000
  num_validation_steps: 2500
  disc_start_step: 50000
  save_ckpt_per_iter: 5000
