dataset:
  name: VideoDiffFrames_woCP
  batch_size: 6
  limit: 0.5
  img_size: 128
  num_frames: 20
  num_workers: 8
  shuffle: False
  pin_memory: False
  train:
    idspath: datasets/KTH/frames/trainval_FPS25_ids.json
    usedfps: FPS25
    datapath: datasets/KTH/frames
  val:
    idspath: ~
    usedfps: FPS25
    datapath: datasets/KTH/frames/test

model:
  name: MoCoVQVAE_wCD_shareCB
  pretrain_path: ~ #experiments/MoCoVQVAEwCDsCB_KTH_im128_20frames_th10_woCP_2022-10-22-11-22-32/MoCoVQVAE_wCD_shareCB_iter250000.pth
  checkpoint_path: ~
  load_strict: False

  num_hiddens: 256
  num_residual_layers: 4
  num_residual_hiddens: 128

  embedding_dim: 256
  num_embeddings: 24576 # [4096, 9182, ...]

  ds_content: 2
  ds_motion: 4 # 20x8x8-1280
  ds_identity: 3 # 16x16-256
  ds_background: 2 # 32x32-1024
  suf_method: conv # [avg_pool, max_pool, conv]
  decoder_type: decoder_wTA
  encoder_mo_type: default

  num_head: 4
  num_group: 4
  time_head: 10

  ABS_weight: 1.0
  MSE_weight: 0.0
  Gen_weight: 0.1

  decay: 0.99
  if_augcb: 2
  commitment_cost: 0.25
  with_lpips: True
  lpips_factor: 1.0

  disc_name: patchwise
  disc_opt:
    input_nc: 60    # 3channel * 20frames
    n_layers: 2
    ndf: 32
    input_formation: concat_c

train:
  device: ~ # the parameter will be given when training
  local_rank: ~ # the parameter will be given when training
  WANDB_OPEN: True
  find_unused_parameters: True

  # model params
  exp_name: MoCoVQVAEwCDsCB_KTH_im128_10to10_woCP_wodisc
  save_path: experiments/

  # train params
  learning_rate: !!float 2e-4
  LRsche: False

  # steps
  num_epochs: 100000
  num_warmup_steps: 0  # null if want to set 0.1 warm up
  num_training_updates: 250000
  num_validation_steps: 2500
  disc_start_step: 250000
  fullbgid_start: 0
  save_ckpt_per_iter: 5000
