dataset:
  name: VideoDiffFrames
  batch_size: 4
  limit: 0.5
  img_size: 256
  num_frames: 8
  num_workers: 2
  shuffle: False
  pin_memory: True
  train:
    idspath: /home/zhongguokexueyuanzidonghuayanjiusuo/mzsun/datasets/UCF-101/train_ids.json
    datapath: /home/zhongguokexueyuanzidonghuayanjiusuo/datasets/UCF-101/frames_fps20
  val:
    idspath: /home/zhongguokexueyuanzidonghuayanjiusuo/mzsun/datasets/UCF-101/valid_ids.json
    datapath: /home/zhongguokexueyuanzidonghuayanjiusuo/datasets/UCF-101/frames_fps20

model:
  name: MoCoVQVAE_wICD
  pretrain_path: experiments/MoCoVQVAEwoPA_ENmoAttnRes_2022-04-28-20-21-59/MoCoVQVAE_woPA_iter100000.pth
  checkpoint_path: ~
  load_strict: False

  num_hiddens: 256
  num_residual_layers: 4
  num_residual_hiddens: 128

  embedding_dim_c: 256
  embedding_dim_m: 256
  num_embeddings_c: 8192
  num_embeddings_m: 8192 # [4096, 9182, ...]

  ds_motion: 5
  ds_content: 3
  suf_method: conv # [avg_pool, max_pool, conv]
  decoder_type: decoder_woPA
  encoder_mo_type: encoder_mo_attn_res

  num_head: 4
  num_group: 4

  ABS_weight: 1.0
  MSE_weight: 0.0
  IMGGen_weight: 0.1
  CATGen_weight: 0.1

  decay: 0.99
  commitment_cost: 0.25
  with_lpips: True
  lpips_factor: 1.0

  cat_disc_opt:
    input_nc: 24    # 3channel * 8frames
    n_layers: 3
    ndf: 64
    input_formation: concat_c

  img_disc_opt:
    input_nc: 3    # 3channel * 1frames
    n_layers: 3
    ndf: 64
    input_formation: imgs

train:
  device: ~ # the parameter will be given when training
  local_rank: ~ # the parameter will be given when training
  WANDB_OPEN: True
  find_unused_parameters: True

  # model params
  exp_name: MoCoVQVAEwICD_ENmoAttnRes_pretrain10W_ID2e-1_CD2e-1
  save_path: experiments/

  # train params
  learning_rate: !!float 1e-4
  LRsche: True

  # steps
  num_epochs: 2000
  num_warmup_steps: 0  # null if want to set 0.1 warm up
  num_training_updates: 100000
  num_validation_steps: 2500
  disc_start_step: 1000
  save_ckpt_per_iter: 5000
