dataset:
  name: VideoDiffFrames
  batch_size: 4
  limit: 0.5
  img_size: 256
  num_frames: 8
  num_workers: 2
  shuffle: False
  pin_memory: True
  train:
    idspath: /home/zhongguokexueyuanzidonghuayanjiusuo/mzsun/datasets/UCF-101/train_ids.json
    datapath: /home/zhongguokexueyuanzidonghuayanjiusuo/datasets/UCF-101/frames_fps20
  val:
    idspath: /home/zhongguokexueyuanzidonghuayanjiusuo/mzsun/datasets/UCF-101/valid_ids.json
    datapath: /home/zhongguokexueyuanzidonghuayanjiusuo/datasets/UCF-101/frames_fps20

model:
  name: MoCoVQVAE_wID
  pretrain_path: ~
  load_strict: True
  checkpoint_path: ~

  num_hiddens: 256
  num_residual_layers: 4
  num_residual_hiddens: 128

  embedding_dim_c: 256
  embedding_dim_m: 256
  num_embeddings_c: 8192
  num_embeddings_m: 8192 # [4096, 9182, ...]

  ds_motion: 5
  ds_content: 3
  suf_method: conv # [avg_pool, max_pool, conv]

  num_head: 4
  num_group: 4

  ABS_weight: 0.5
  MSE_weight: 0.25

  decay: 0.99
  commitment_cost: 0.25
  with_lpips: True
  lpips_factor: 1.0

  disc_name: patchwise
  disc_opt:
    input_nc: 3
    n_layers: 3
    ndf: 64

train:
  device: ~ # the parameter will be given when training
  local_rank: ~ # the parameter will be given when training
  WANDB_OPEN: True
  find_unused_parameters: True

  # model params
  exp_name: MoCoVQVAEwID_ABS0.5_MSE0.25
  save_path: experiments/

  # train params
  learning_rate: !!float 1e-4
  LRsche: True

  # steps
  num_epochs: 2000
  num_warmup_steps: 0  # null if want to set 0.1 warm up
  num_training_updates: 100000
  num_validation_steps: 2500
  disc_start_step: 10000
  save_ckpt_per_iter: 5000
