dataset:
#  name: VideoDiffFrames
  name: VideoDiffFrames_fromnpy
  batch_size: 32
  limit: 0.5
  img_size: 64
  num_frames: 10
  num_workers: 8
  shuffle: False
  pin_memory: False
  train:
    idspath: ~
    usedfps: FPS30
    datapath: datasets/KITTI/convert_frames/train10
#    datapath: datasets/KITTI/frames/train
  val:
    idspath: ~
    usedfps: FPS30
    datapath: datasets/KITTI/convert_frames/test10
#    datapath: datasets/KITTI/frames/test

model:
  name: MoCoVQVAE_wCD_shareCB
  pretrain_path: ~
  checkpoint_path: ~
  load_strict: True

  num_hiddens: 256
  num_residual_layers: 4
  num_residual_hiddens: 128

  embedding_dim: 256
  num_embeddings: 10000 # [4096, 9182, ...]

  ds_content: 2
  ds_motion: 3
  ds_identity: 2
  ds_background: 2
  suf_method: conv # [avg_pool, max_pool, conv]
  decoder_type: decoder_woPA
  encoder_mo_type: default

  num_head: 4
  num_group: 4
  time_head: 5

  ABS_weight: 1.0
  MSE_weight: 0.0
  Gen_weight: 0.1

  decay: 0.99
  if_augcb: 2
  commitment_cost: 0.25
  with_lpips: True
  lpips_factor: 1.0

  disc_name: patchwise
  disc_opt:
    input_nc: 30    # 3channel * 10frames
    n_layers: 2
    ndf: 32
    input_formation: concat_c

train:
  device: ~ # the parameter will be given when training
  local_rank: ~ # the parameter will be given when training
  WANDB_OPEN: True
  find_unused_parameters: True

  # model params
  exp_name: MoCoVQVAEwCDsCB_KITTI_im64_10frames_f2_th5_cb1W_como
  save_path: experiments/

  # train params
  learning_rate: !!float 2e-4
  LRsche: True

  # steps
  num_epochs: 1000000
  num_warmup_steps: 0  # null if want to set 0.1 warm up
  num_training_updates: 250000
  num_validation_steps: 2500
  disc_start_step: 50000
  fullbgid_start: 0
  save_ckpt_per_iter: 5000
